_target_: src.models.flower_module.FlowerLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 10
  gamma: 0.1

net:
  _target_: src.models.components.efficientnet_b5_ns.FlowerNet
  n_classes: 104
  model_name: tf_efficientnet_b5_ns
  use_fc: False
  fc_dim: 512
  dropout: 0.0
  pretrained: False
